Provide an Node-only development option for Elm development
kyoung/unconf pull request #27
Opened 2019-04-06 18:19 UTC by bholtbholt

I don't have a Python environment on my computer, and I've never used one so I assumed I'd get stuck somewhere in setup while working on the Elm portion. Since Elm is strongly typed, I was able to understand the contract between the front-end and back-end and create a mock-server to use.

This PR adds `json-server` with a mock database so it's easy to create various states on the front-end while not affecting the back-end code (or even running it). It's not required for the project, but it makes Elm and CSS development much easier 😄 

I filled out the README with a step by step guide

2019-05-19 03:08 UTC, kyoung requested changes
This all seems like a lot more work than just installing python3 :P but I'm happy to get it through so I can get on to the restyled PR. My only request is the commented changes to the docs, and perhaps rather than only supplying the one sample data.json, we prepare several states (voting with a mix of voted and not, scheduled/pitching) and have make targets that symlink or copy each to the canonical data set for quick switching between states, eg. `make state-voting` `make state-schedule` etc.

2019-05-19 03:08 UTC, kyoung commented on README.md
> +1. Duplicate `./json-server/db.sample.json` as `./json-server/db.json`
this is a great readme addition, but could be made better here by something more along the lines of:
1. Duplicate the sample dataset (optional) with `cp ./json-server/db.sample.json ./json-server/db.json`

2019-05-19 03:08 UTC, kyoung commented on README.md
> +where `0` maps to the Pitching UUID, and `1` maps to the Schedule UUID.
are these UUIDs in the data json?

2019-05-19 16:21 UTC, bholtbholt commented on README.md
> +where `0` maps to the Pitching UUID, and `1` maps to the Schedule UUID.
Yep, they are: https://github.com/kyoung/unconf/pull/27/files#diff-bc5eebc14fee40b23a29e5a3bbdbc4e9R4 and https://github.com/kyoung/unconf/pull/27/files#diff-bc5eebc14fee40b23a29e5a3bbdbc4e9R8.

These UUIDs are setup to be easy to switch, as 0 and 1. I've [configured](https://github.com/kyoung/unconf/pull/27/files#diff-b281664d0b65dbb811f40ba3b179455dR2) the JSON route to "pick" one of the UUIDs on load, which any contributor can change.

As you've mentioned in the review, I'll set this up so it doesn't need to be changed and users can easily restart the server in the correct mode.

2019-05-19 16:36 UTC, bholtbholt commented
_Maybe_ a bit of work compared to installing Python. This took roughly an hour to set up and I guessed getting a successful Python environment, then filling the app and managing states would take me more than that, simply because I'm not that familiar with it.

To be clear **this is not required for the style changes**. It was the way I developed it because of the above Python concerns, but the PRs are completely independent.

Requested changes coming shortly!

2019-05-19 16:48 UTC, bholtbholt commented
I like the suggestion of `pitching` and `schedule`. That's much easier to switch back and forth without getting into the internals. 😄 

Pushed those changes, and have attached screenshots (old design) of the two modes.

![Screen Shot 2019-05-19 at 9 43 20 AM](https://user-images.githubusercontent.com/4933622/57985349-48776280-7a1b-11e9-8d9d-22747314dba9.png)
![Screen Shot 2019-05-19 at 9 43 32 AM](https://user-images.githubusercontent.com/4933622/57985350-48776280-7a1b-11e9-94b4-4b6dd061b3ca.png)

2019-05-21 04:44 UTC, kyoung approved these changes

2019-05-21 04:44 UTC, merged